### ISSUE TITLE
Support Django 3.1

### ISSUE THREAD

**Issue by uri-rodberg** [matthiask/django-translated-fields#21]
django-translated-fields doesn't work with Django 3.1 alpha 1.

I installed Django 3.1 alpha 1 with `pip install --upgrade --pre django`, but my project can't run even `make_migrations` or `migrate`. I receive an exception when I try to import `from translated_fields import to_attribute`.

I'm using `django-translated-fields==0.8.0`.

**Comment by matthiask** [comment]
Hi, I'm a bit surprised. Tests seem to pass https://travis-ci.org/github/matthiask/django-translated-fields/builds/687015996 so why would this fail?

Maybe there's a circular import somewhere?

**Comment by uri-rodberg** [comment]
I don't know, everything works for me with Django 3.0.6, and when I install Django 3.1a1, it fails.

I receive the following error:

```
from translated_fields import to_attribute as translated_fields_to_attribute

ImportError: cannot import name 'to_attribute'
```

**Comment by matthiask** [comment]
Can you please try importing `to_attribute` from `translated_fields.fields`? Importing from `translated_fields` directly might shadow the real reason for the import error.

**Comment by matthiask** [comment]
Oh right. The error seems to have been fixed in https://github.com/matthiask/django-translated-fields/commit/d9f6c7e03976e24845f0b8b1e74bb7ef35f92da9

I'll prepare a release then.

**Comment by uri-rodberg** [comment]
I also checked your code and I found out that in [translated_fields/__init__.py](https://github.com/matthiask/django-translated-fields/blob/master/translated_fields/__init__.py), there is try..except which may confuse developers why imports don't work. When I removed this try..except I received this error:

```
from django.db.models import FieldDoesNotExist
ImportError: cannot import name 'FieldDoesNotExist'
```

**Comment by matthiask** [comment]
Yes, maybe I should stop doing this (or rethink the way it is done currently).

Anyway, installing `django-translated-fields==0.9` should fix the problems.

Except if you're using django-debug-toolbar, that one doesn't work in the released version either. I should probably push a new release there too :)

**Comment by uri-rodberg** [comment]
Is it better to import my imports from `translated_fields.fields` and `translated_fields.admin` instead of importing directly from `translated_fields`? I checked your documentation and it says to import directly.

**Comment by matthiask** [comment]
Exposing attributes from other modules in a central location is a good idea (I think) but the implementation sucks. I'd like to fix the code to expose underlying import errors so that we can continue importing directly from `translated_fields`.

**Comment by uri-rodberg** [comment]
Maybe you should just remove the try and except in __init__.

**Comment by matthiask** [comment]
@uri-rodberg The reason for the try...except is that I also import the `__init__.py` file to determine the current version from `setup.py`. I could and should probably do this differently now (via setup.cfg or something) but...
